# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6cfd9a0a656451fa9cc14656f29ecaaf"
name = "manage-prices"
handle = "manage-prices-1"
application_url = "https://therapy-november-grave-applicable.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "catalog-test-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://therapy-november-grave-applicable.trycloudflare.com/auth/callback",
  "https://therapy-november-grave-applicable.trycloudflare.com/auth/shopify/callback",
  "https://therapy-november-grave-applicable.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
